kind: List
metadata: {}
apiVersion: v1
items:  
  - apiVersion: v1
    kind: ImageStream
    metadata: 
      name: hello-openshift-source
    spec: 
      tags: 
        - from: 
            kind: DockerImage
            name: openshift/hello-openshift
          name: latest
  - apiVersion: v1
    kind: ImageStream
    metadata: 
      name: hello-openshift
  - apiVersion: v1
    kind: DeploymentConfig
    metadata: 
      name: hello-app-http
    spec: 
      replicas: 1
      selector: 
        app: hello-app-http
        deploymentconfig: hello-app-http
      strategy: ~
      template: 
        metadata: 
          labels: 
            app: hello-app-http
            deploymentconfig: hello-app-http
        spec: 
          containers: 
            - image: " "
              name: hello-app-http
              ports: 
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8888
                  protocol: TCP
      test: false
      triggers: 
        - type: ConfigChange
        - imageChangeParams: 
            automatic: true
            containerNames: 
              - hello-app-http
            from: 
              kind: ImageStreamTag
              name: "hello-openshift:latest"
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata: 
      name: hello-app-http
    spec: 
      ports: 
        - name: web
          port: 80
          protocol: TCP
          targetPort: 8080
      selector: 
        app: hello-app-http
        deploymentconfig: hello-app-http
  - apiVersion: v1
    kind: Route
    metadata: 
      name: hello-app-http
    spec: 
      port: 
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Allow
        termination: edge
      to: 
        kind: Service
        name: hello-app-http
  - apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: hello-build-http
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "hello-openshift:latest"
      source: 
        dockerfile: |-
            FROM openshift/hello-openshift
        type: Dockerfile
      strategy: 
        dockerStrategy: 
          from: 
            kind: ImageStreamTag
            name: "hello-openshift-source:latest"
        type: Docker
      triggers: 
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
